In [9]:
print("Hello World")

Hello World


In [10]:
!dir

 Volume in drive D is LENOVO
 Volume Serial Number is 0299-ED51

 Directory of D:\handson\Module1\B2_24_25Sept

24-09-2020  08:59    <DIR>          .
24-09-2020  08:59    <DIR>          ..
24-09-2020  08:41    <DIR>          .ipynb_checkpoints
24-09-2020  08:59             8,169 Day1.ipynb
23-09-2020  08:37               115 README.md
24-09-2020  08:56                14 test.txt
24-09-2020  08:41                72 Untitled.ipynb
               4 File(s)          8,370 bytes
               3 Dir(s)   5,769,412,608 bytes free


In [4]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [5]:
%pwd

'D:\\handson\\Module1\\B2_24_25Sept'

In [6]:
%pwd?

In [7]:
%%writefile test.txt
hello World!

Writing test.txt


In [8]:
with open('test.txt', 'rt') as f:
    print(f.read())

hello World!



# py refresher

In [12]:
# data types
a = 1
f = 1.2
b = True
s = 'Hello' # "Hello"  # immutable
lst = [1, 1.2, "OK", [1,2,3]] #Mutable
st = { 1,2,3 } #Mutable, Duplicates - Not allowed
ed = { 'ok' : 2, 'nok': 3} #keys are like set

In [14]:
if a == 1 and f <= 0:
    print(a)
elif f >= 1.0 or s == "OK":
    print(f)
else:
    print("other")

1.2


In [25]:
#mutability/immutability
t = (1,2,3) #immutable
try:
    s[0] = 'K'  #Error
    t[0] = 20    
except Exception:
    print("error")
lst[-1] = 30
lst.append(40)
print(lst)
st.add(40)
print(st)
ed['new'] = [1,2,3]
print(ed)

error
[1, 1.2, 'OK', 30, 30, 30, 30, 30, 30, 40]
{40, 1, 2, 3}
{'ok': 2, 'nok': 3, 'new': [1, 2, 3]}


In [28]:
#empty
elst = [] ; edict = {} ; estr = '' ; eset = set(); etuple = ()
#length
print(len(lst), len(t), len(st), len(s), len(ed))
#Accesing
s[0]  #index starts from 0
lst[-1] #- means starts from RHS 
lst[0:3] #start:end:step , default: step=1, end = end of the collection, start=start of the collection
#indexing not possible in set 
ed['nok']

10 3 4 5 3


3

In [34]:
#containment checking
print( 2  not in lst, 3 in st, 1 in t, 'O' in s, 'nok' in ed)
#iteration 
for e in lst:
    print(e)
for k in ed:
    print(k, ed[k])
#example - comprehension
el = []
for e in lst:
    if type(e) is not str:  #type(s) = <class 'str'>
        el.append( e + 20)
print(el)
#comprehension
el = [e + 20 for e in lst if type(e) is not str]
print(el)
{e + 20 for e in lst if type(e) is not str} # set comprehension
{e : e + 20 for e in lst if type(e) is not str} #dict comprehension

True True True False True
1
1.2
OK
30
30
30
30
30
30
40
ok 2
nok 3
new [1, 2, 3]
[21, 21.2, 50, 50, 50, 50, 50, 50, 60]
[21, 21.2, 50, 50, 50, 50, 50, 50, 60]


In [37]:
#Nested datastructure 
d2 = {'ok' : 2, 'nok': 3}
c = 0
while c < 3:
    d2 = {'ok': [d2]}
    c += 1
print(d2)

{'ok': [{'ok': [{'ok': [{'ok': 2, 'nok': 3}]}]}]}


In [47]:
# can you change 'nok' value to 30?
type(d2), d2.keys(), d2['ok'], type(d2['ok']), len(d2['ok']), d2['ok'][0]
#result
d2['ok'][0]['ok'][0]['ok'][0]['nok'] = 30
print(d2)
#module imports
import pprint
pprint.pprint(d2)
#check 
dir(pprint) # all methods of pprint
help(pprint.pprint) #to see help

{'ok': [{'ok': [{'ok': [{'ok': 2, 'nok': 30}]}]}]}
{'ok': [{'ok': [{'ok': [{'nok': 30, 'ok': 2}]}]}]}
Help on function pprint in module pprint:

pprint(object, stream=None, indent=1, width=80, depth=None, *, compact=False)
    Pretty-print a Python object to a stream [default is sys.stdout].



In [52]:
import sys
sys.path

['D:\\handson\\Module1\\B2_24_25Sept',
 'C:\\Anaconda3\\envs\\aiml\\python37.zip',
 'C:\\Anaconda3\\envs\\aiml\\DLLs',
 'C:\\Anaconda3\\envs\\aiml\\lib',
 'C:\\Anaconda3\\envs\\aiml',
 '',
 'C:\\Anaconda3\\envs\\aiml\\lib\\site-packages',
 'C:\\Anaconda3\\envs\\aiml\\lib\\site-packages\\win32',
 'C:\\Anaconda3\\envs\\aiml\\lib\\site-packages\\win32\\lib',
 'C:\\Anaconda3\\envs\\aiml\\lib\\site-packages\\Pythonwin',
 'C:\\Anaconda3\\envs\\aiml\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\das\\.ipython']

In [61]:
%%writefile mex.py
def my_add(x,y):
    return x+y

def my_add1(x,y=20):
    return x+y

Overwriting mex.py


In [62]:
import mex
import importlib
importlib.reload(mex)
mex.my_add(2,3)  # positional arg passing
mex.my_add(y=3, x=2) #keyword based arg passing
mex.my_add(2, y=3) #mix of above, only positional should be first
mex.my_add1(20)  #y is default

40

In [69]:
lsw = ['a', 'aa', 'xyz', 'x']
sorted(lsw) #based on natural sorting order of string
def p(e): # e is datatype of each element 
    return len(e)
#HOF
sorted(lsw, key=p, reverse=True) #sorting by key 
#OR
sorted(lsw, key=lambda e: len(e), reverse=True) # constraint: one expression only can be returned
p('aa')
(lambda e: len(e))('aa')
type(p)
p

<function __main__.p(e)>

# Introducing numpy

Create two lists x,y of 100K random numbers. 
Measure the time taken to elementwise addition of those two lists


In [70]:
a = 1
b = 1
%timeit a+b

143 ns ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [74]:
import random
n = 100000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]
x[:3], y[:3]

z = [x[i] + y[i] for i in range(n)]
%timeit [x[i] + y[i] for i in range(n)]

38.7 ms ± 5.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [76]:
import numpy as np
xn = np.array(x)
yn = np.array(y)
zn = xn + yn # API is simpler
#performance is better
%timeit xn+yn

249 µs ± 15.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [77]:
z[:3], zn[:3]

([0.6726668555395133, 1.3029464708389833, 0.9331093638659949],
 array([0.67266686, 1.30294647, 0.93310936]))

In [79]:
len(dir(np)), len(dir(np.random))

(620, 81)

In [80]:
#Creation 
x = np.array([1,2,3])
y = np.linspace(2.0, 3.0, num=3) # logspace 
z = np.arange(12).reshape( (2,6) )
ru = np.random.random( (2,6) ) #uniform random 
rn = np.random.normal(0, 1, (2,6) ) # mu=0, var=1

In [83]:
#ops 
ru.shape, ru.ndim, ru.dtype

((2, 6), 2, dtype('float64'))

In [91]:
#Access
x[0]
z[0,0]
z[:, 0:2], z[0, :] # : is nothing but slicing ie start:end:step
z[ z> 2]
z[ (z>2) & (z < 4)] # &, | , not 
z[0,0] = 20

In [101]:
#elementwise 
np.sqrt(z)
ru + rn  #both are having dimensions
x/y
z + 2
ru * rn # elementwise 
#matrix 
np.mat(ru) * np.mat(rn).T  #.T is transpose
np.mat(ru).I  #inverse
#dir(np.mat(ru))

matrix([[ 0.29324775, -0.09008593],
        [-0.74651353,  0.92397673],
        [ 0.90613584, -0.61936724],
        [-0.17791049,  0.55441732],
        [ 0.47878205, -0.02019018],
        [ 0.57490072, -0.37442538]])

In [107]:
# axis based , for 2D, axis=0=row , axis=1=column
print(z,
      np.sum(z),
      np.sum(z, axis=0), #row varying, columnwise
      np.sum(z, axis=1)) #col varying, rowwise

#(5,6,7,8)
zz = np.arange(5*6*7*8).reshape( (5,6,7,8))
np.sum(zz, axis=2).shape

[[20  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 86 [26  8 10 12 14 16] [35 51]


(5, 6, 8)